package model;

import java.io.Serializable;

/**
 * Car ���f���N���X.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** carid. */
	private Integer userid;

	/** pinpaiming. */
	private String xingming;

	/** xilie. */
	private String xingbie;

	/** shoujia. */
	private Integer nianling;

	/** gonglishu. */
	private Integer dianhuahaoma;

	/** yanse. */
	private String dianziyoujian;

	;

	/**
	 * �R���X�g���N�^.
	 */
	public User() {
	}

	/**
	 * carid ��ݒ肵�܂�?.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * carid ���擾���܂�.
	 * 
	 * @return carid
	 */
	public Integer getCarid() {
		return this.userid;
	}

	/**
	 * pinpaiming ��ݒ肵�܂�?.
	 * 
	 * @param pinpaiming
	 *            pinpaiming
	 */
	public void setxingming(String xingming) {
		this.xingming = xingming;
	}

	/**
	 * pinpaiming ���擾���܂�.
	 * 
	 * @return pinpaiming
	 */
	public String getXingming() {
		return this.xingming;
	}

	/**
	 * xilie ��ݒ肵�܂�?.
	 * 
	 * @param xilie
	 *            xilie
	 */
	public void setXingbie(String xingbie) {
		this.xingbie = xingbie;
	}

	/**
	 * xilie ���擾���܂�.
	 * 
	 * @return xilie
	 */
	public String getXingbie() {
		return this.xingbie;
	}

	/**
	 * shoujia ��ݒ肵�܂�?.
	 * 
	 * @param shoujia
	 *            shoujia
	 */
	public void setNianling(Integer nianling) {
		this.nianling = nianling;
	}

	/**
	 * shoujia ���擾���܂�.
	 * 
	 * @return shoujia
	 */
	public Integer getNianling() {
		return this.nianling;
	}

	/**
	 * gonglishu ��ݒ肵�܂�?.
	 * 
	 * @param gonglishu
	 *            gonglishu
	 */
	public void setDianhuahaoma(Integer dianhuahaoma) {
		this.dianhuahaoma = dianhuahaoma;
	}

	/**
	 * gonglishu ���擾���܂�.
	 * 
	 * @return gonglishu
	 */
	public Integer getDianhuahaoma() {
		return this.dianhuahaoma;
	}

	/**
	 * yanse ��ݒ肵�܂�?.
	 * 
	 * @param yanse
	 *            yanse
	 */
	public void setDianziyoujian(String dianziyoujian) {
		this.dianziyoujian = dianziyoujian;
	}

	/**
	 * yanse ���擾���܂�.
	 * 
	 * @return yanse
	 */
	public String getDianziyoujian() {
		return this.dianziyoujian;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}

		return true;
	}

}
